version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: always

  frontend:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always
